name: deploy-website
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Cache deno deps
        run: deno cache ./package-as-npm.ts ./src/ts/deps.ts
        working-directory: lib/
      - name: Build library
        run: ./build.sh
        working-directory: lib/

      - name: Install frontend deps
        run: |
          npm install
        working-directory: frontend/
      - name: Build frontend
        run: |
          npm run lint
          npm run build
        working-directory: frontend/
        
      - name: Deploy frontend to Github Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist
          repository-name: arstulke/arstulke.github.io
          branch: main
          commit-message: "Deploying apps/sign-detection"
          target-folder: apps/sign-detection
          ssh-key: ${{ secrets.DEPLOY_GH_PAGES_KEY }}
