# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "sign-detection" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - uses: mymindstorm/setup-emsdk@v11

      - name: Cache deno deps
        run: deno cache ./build.ts ./src/ts/deps.ts
        working-directory: sign-detection/lib/
      - name: Build library
        run: ./build.ts
        working-directory: sign-detection/lib/

      - name: Install frontend deps
        run: |
          npm install
          npm ci
        working-directory: sign-detection/frontend/
      - name: Build frontend
        run: |
          npm run lint
          npm run build
        working-directory: sign-detection/frontend/
        
      - name: Deploy frontend to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: sign-detection/frontend/dist
          repository-name: arstulke/arstulke.github.io
          branch: main
          commit-message: "Deploying apps/sign-detection"
          target-folder: apps/sign-detection
          ssh-key: ${{ secrets.DEPLOY_GH_PAGES_KEY }}
